# Generated by Django 5.1 on 2024-08-29 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_tag_alter_profile_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='Sumury', max_length=200),
            preserve_default=False,
        ),
    ]
