# Generated by Django 5.1 on 2024-08-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_date_published_article_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='url',
        ),
    ]
