# Generated by Django 5.1 on 2024-08-30 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_author_remove_article_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
