# Generated by Django 5.1 on 2024-09-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_user_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Editeur', 'Editeur'), ('Admin', 'Administrateur')], default='Editeur', max_length=10),
        ),
    ]
